---
- name: Update repositories cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: nrpe_plugin_dir_default
  set_fact:
    nrpe_plugin_dir: /usr/lib/nagios/plugins

- name: nrpe_plugin_dir_1
  set_fact:
    nrpe_plugin_dir: /usr/lib64/nagios/plugins
  when: ansible_os_family == "RedHat" and ansible_architecture != "i686"

- name: import epel gpg key
  rpm_key:
    key: "{{ epel_repo_gpg_key_path }}"
    state: present
  tags:
    - epel
  when: ansible_os_family == 'RedHat'

- name: install epel repo
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  tags:
    - epel
  when: ansible_os_family == 'RedHat'

# To enable powertools, see next step
- name: Install dnf-plugins-core
  yum:
    name: dnf-plugins-core
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int > 7

# For certain Perl modules to be available
- name: Install powertools
  command: dnf config-manager --set-enabled powertools
  when:
    - ansible_os_family == 'RedHat'
    - not ansible_distribution == 'RedHat'
    - ansible_distribution_major_version|int > 7
  changed_when: false

# The equivalent of powertools on RHEL. Unclear if still required.
- name: Install powertools
  command: subscription-manager repos --enable "codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version|int > 7
  changed_when: false
  failed_when: false

- name: Install NRPE
  package: >
    name={{ nrpe_package_name }}
    state=present

- name: Install Plugins
  package: >
    name={{ item }}
    state=present
  when: ansible_os_family == 'RedHat'
  with_items:
    - nagios-plugins-all

- name: Enable NRPE service
  service: >
    name={{ nrpe_service_name }}
    state=started
    enabled=yes

- name: Install check_mem plugin
  copy: src=files/check_mem dest={{ nrpe_plugin_dir }}/check_mem mode=755

- name: NRPE config file
  template:
    src: nrpe.cfg
    dest: /etc/nagios/nrpe.cfg
    owner: root
    group: root
    mode: 0644
  notify: restart nrpe

# for redhat
- name: nrpe.d dir
  file:
    path: "{{ nrpe_conf_dir }}/nrpe.d"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: NRPE checks
  template:
    src: nrpe_check.cfg
    dest: "{{ nrpe_conf_dir }}/nrpe.d/{{ item.key }}.cfg"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ nrpe_checks }}"
  notify: restart nrpe
